name: Build

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - 'feat/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'

jobs:
  feature-build:
    uses: wqshmed/common_workflows/.github/workflows/feature-branch.yml@main
    with:
      java_version: '21'
      docker_image_name: 'wqshmed/claude-api-bot'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}