name: Build

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    uses: wqshmed/common_workflows/.github/workflows/main-branch.yml@main
    with:
      java_version: '21'
      image_name: 'wqshmed/claude-api-bot'
      sonar_project_key: 'claude-api-bot'
      sonar_organization: 'wqshmed-sonar'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}