name: Build

on:
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: '21'
  IMAGE_NAME: 'wqshmed/claude-api-bot'

jobs:
  pipeline:
    uses: wqshmed/common_workflows/.github/workflows/main.yml@main
    with:
      java_version: ${{ env.JAVA_VERSION }}
      docker_image_name: ${{ env.IMAGE_NAME }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}